### ISSUE TITLE
zeromq error

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/iceprod#100]
Likely accessing the ioloop from outside the thread:

```
Traceback (most recent call last):
  File "/scratch/simprod/iceprod2/iceprod/server/pool.py", line 531, in _runner
    f(*a,**k)
  File "/scratch/simprod/iceprod2/iceprod/server/dbmethods/rpc.py", line 271, in _rpc_finish_task_blocking
    task_stat_id = self.db._increment_id_helper('task_stat',conn)
  File "/scratch/simprod/iceprod2/iceprod/server/modules/db.py", line 606, in _increment_id_helper
    raise Exception('failed to run query')
Exception: failed to run query
2016-06-01 15:05:35,733 WARNING zeromq : ioloop error
Traceback (most recent call last):
  File "/scratch/simprod/iceprod2/iceprod/server/zeromq.py", line 46, in run
    self.io_loop.start()
  File "/cvmfs/icecube.opensciencegrid.org/iceprod/master/RHEL_6_x86_64/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "/cvmfs/icecube.opensciencegrid.org/iceprod/master/RHEL_6_x86_64/lib/python2.7/site-packages/tornado/ioloop.py", line 811, in start
    heapq.heappop(self._timeouts)
RuntimeError: list changed size during iteration
```

**Comment by dsschult** [comment]
At a minimum, we need to gracefully recover from errors like this, restarting messaging.

**Comment by dsschult** [comment]
error is still there

**Comment by dsschult** [comment]
#124 will eliminate the problem by eliminating internal RPC.
